name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build
        run: pnpm build

      - name: Publish
        run: npm publish --provenance --access public
